apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- namespace.yaml
namespace: namespace-lister
configMapGenerator:
- behavior: merge
  files:
  - traefik.yaml=./proxy-config/traefik.yaml
  name: traefik-sidecar-static-config
  options:
    disableNameSuffixHash: true
- behavior: merge
  files:
  - config.yaml=./proxy-config/dynamic/config.yaml
  name: traefik-sidecar-dynamic-config
  options:
    disableNameSuffixHash: true
