apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ns.yaml
- https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/24.0.2/kubernetes/kubernetes.yml
- db.yaml
- configure-keycloak.yaml
- ingress.yaml
- certificate.yaml
- root-ca-cluster-issuer.yaml
namespace: keycloak

patches:
- patch: |
    - op: add
      path: /metadata/annotations/ignore-check.kube-linter.io~1no-read-only-root-fs
      value: "This deployment needs to have write permissions"
  target:
    kind: Deployment
    name: keycloak-operator
- patch: |
    - op: add
      path: /metadata/annotations/ignore-check.kube-linter.io~1run-as-non-root
      value: "This deployment needs to have root permissions"
  target:
    kind: Deployment
    name: keycloak-operator
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: 200m
          memory: 200Mi
        limits:
          cpu: 300m
          memory: 300Mi
  target:
    kind: Deployment
    name: keycloak-operator
secretGenerator:
- literals:
  - POSTGRES_USER=keycloak
  - POSTGRES_PASSWORD=keycloak
  name: keycloak-db-secret
  options:
    disableNameSuffixHash: true
  type: Opaque
