apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        # Goal: Rewrite rules for in-cluster access to a service using the same FQDN as for external access
        # subdomain names resolves to the IP address of the kubernetes ingress service and then will become ingress-nginx-controller.ingress-nginx.svc.cluster.local
        rewrite stop {
            name regex (.*).namespacelister.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local answer auto
        }
        # host name resolves to the IP address of the kubernetes ingress service
        rewrite name exact namespacelister.localtest.me ingress-nginx-controller.ingress-nginx.svc.cluster.local
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
